name = "Ultimate Twitch Modpack"
author = "IsaiahCreati"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b866e1c19248698a0d3650f8e6df0d39a1be733acee10841f2880b98730bae39"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"

[options]
acceptable-game-versions = ["26.1.2"]
