name = "Ultimate Twitch Modpack"
author = "IsaiahCreati"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af917e2d1f3ab01a649ec319f696eef749c7a599f6e06de5bb86277849796e90"

[versions]
minecraft = "26.1"
neoforge = "26.1.2.74"

[options]
acceptable-game-versions = ["26.1", "1.21.10", "1.21.11"]
