name = "Ultimate Twitch Modpack"
author = "IsaiahCreati"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b18604f6800bedc37615d160126e362abe584cfd3e3c9d00aed9f70f4aab28af"

[versions]
minecraft = "26.1"
neoforge = "26.1.2.74"

[options]
acceptable-game-versions = ["26.1", "1.21.10", "1.21.11"]
