name: Publish
on:
  workflow_dispatch:
  push:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      # Removed Gradle Publish Step
#      - name: CurseForge Publish
#        run: ./gradlew curseforge -PcurseApiKey=${CURSE_API_KEY}
#        env:
#          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
#          BUILD_NUMBER: ${{ github.run_number }}
#        continue-on-error: true
#      - name: Modrinth Publish
#        run: ./gradlew modrinth -PmodrinthToken=${MODRINTH_TOKEN}
#        env:
#          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
#          BUILD_NUMBER: ${{ github.run_number }}
#        continue-on-error: true
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
