name: Publish pipeline

on:
  push:
#    tags:
#      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Run Gradle Publish"
        run: ./gradlew publish

      - name: "Extract mod version"
        run: echo "MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          name: "Release v${{ env.MOD_VERSION }}"
          tag_name: "${{ env.MOD_VERSION }}"
          draft: true
          prerelease: false
          files: |
            releases/*

      - name: CurseForge Publish
        run: ./gradlew curseforge -PcurseApiKey=${CURSE_API_KEY}
        env:
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
          BUILD_NUMBER: ${{ github.run_number }}
        continue-on-error: true
# TODO: Make this work, also make the Modrinth repo
#      - name: Modrinth Publish
#        run: ./gradlew modrinth -PmodrinthToken=${MODRINTH_TOKEN}
#        env:
#          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
#          BUILD_NUMBER: ${{ github.run_number }}
#        continue-on-error: true